# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - "main"
  pull_request_target:
    branches: 
      - "**"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  accept:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/github-script@v3.1.0
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        with:
          script: |
            console.log('-- CONTEXT --')
            console.dir(context)
            // console.log('-- GITHUB --')
            // console.dir(github)
            // console.log('-- GITHUB --')
            const [repository_owner, repository_name] = process.env.GITHUB_REPOSITORY.split('/')
            
            console.log(`GITHUB_SHA: ${process.env.GITHUB_SHA}`)
            console.log(`MY_SECRET: ${process.env.MY_SECRET}`)
            console.log(`GITHUB_EVENT_NAME: ${process.env.GITHUB_EVENT_NAME}`)
            console.log(`repository (owner): ${repository_owner}`)
            console.log(`repository (name): ${repository_name}`)
            console.log(`repository (fullname): ${process.env.GITHUB_REPOSITORY}`)
            console.log(`Sender (username): ${context.payload.sender.login}`)
            
            const isCollaborator = (await github.repos.checkCollaborator({owner: repository_owner, repo: repository_name, username: context.payload.sender.login}).catch((err)=>{ return {status: 404}})).status == 204 
            console.log(`Sender (collaborator?): ${isCollaborator}`)
            if (context.eventName == 'pull_request' || context.eventName == 'pull_request_target') {
                const isFromAFork = context.payload.pull_request.head.repo.full_name !== process.env.GITHUB_REPOSITORY
                console.log(`PR > Source Repository (full name): ${context.payload.pull_request.head.repo.full_name}`)
                console.log(`PR > Is From a Fork?: ${isFromAFork}`)
                if(isFromAFork === true) {
                  const labels = (await github.issues.listLabelsOnIssue({owner: repository_owner, repo: repository_name, issue_number:context.payload.pull_request.number})).data
                  const isPrAccepted = labels.find( ({ name }) => name === 'pr/accepted' ) !== undefined
                  console.log(`PR > isPrAccepted: ${isPrAccepted}`)
                  if(isPrAccepted === false) {
                    core.setFailed('Pull Request from non-contributors fork is not accepted. Add a "pr/accepted" label to the PR to accept and trust changes coming from this PR.')   
                  }
                }  
            }

  # This workflow contains a single job called "build"
  build:
    needs: [accept]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  preview-plan:
    if: (github.event_name == 'pull_request' || github.event_name == 'pull_request_target')
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3.1.0
        with:
          script: |
            console.log('Planning PREVIEW deployment')
  preview-deploy:
    needs: [preview-plan]
    runs-on: ubuntu-latest
    environment: 
      name: staging
    steps:
      - uses: actions/github-script@v3.1.0
        with:
          script: |
            console.log('Deploying to Staging')
  test-ready:
    if: (!failure())
    needs: [preview-deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3.1.0
        with:
          script: |
            const [repository_owner, repository_name] = process.env.GITHUB_REPOSITORY.split('/')
            console.log(`GITHUB_SHA: ${process.env.GITHUB_SHA}`)
            console.log(`repository (owner): ${repository_owner}`)
            console.log(`repository (name): ${repository_name}`)
            console.log(`github.checks.listForRef: ${github.checks.listForRef}`)
            const checks1 = (await github.checks.listForRef({owner:repository_owner, repo:repository_name, ref:process.env.GITHUB_SHA})).data
            console.log('checks1')
            console.dir(checks1, {depth: 2})
            const checks2 = (await github.checks.listForRef({owner:repository_owner, repo:repository_name, ref:process.env.GITHUB_SHA, name: 'preview-deploy'})).data
            console.log('checks2')
            console.dir(checks2, {depth: 2})
            const workflowJobs = (await github.actions.listJobsForWorkflowRun({owner:repository_owner, repo:repository_name, run_id:process.env.GITHUB_RUN_ID, filter: 'latest'})).data
            console.log('workflowJobs')
            console.dir(workflowJobs, {depth: 2})
  test-plan:
    if: (!failure()) && (((github.event_name == 'pull_request' || github.event_name == 'pull_request_target') && github.event.pull_request.base.ref == 'main') || (github.event_name == 'push' && github.event.ref == 'refs/heads/main'))
    needs: [test-ready]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3.1.0
        with:
          script: |
            console.log('Planning TEST deployment')
  test-deploy:
    if: (!failure()) && (((github.event_name == 'pull_request' || github.event_name == 'pull_request_target') && github.event.pull_request.base.ref == 'main') || (github.event_name == 'push' && github.event.ref == 'refs/heads/main'))
    needs: [test-plan]
    runs-on: ubuntu-latest
    environment: 
      name: test
    steps:
      - uses: actions/github-script@v3.1.0
        with:
          script: |
            console.log('Deploying to Test')
  production-plan:
    if: (!failure()) && (((github.event_name == 'pull_request' || github.event_name == 'pull_request_target') && github.event.pull_request.base.ref == 'main') || (github.event_name == 'push' && github.event.ref == 'refs/heads/main'))
    needs: [test-deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3.1.0
        with:
          script: |
            console.log('Planning PRODUCTION deployment')
  production-deploy:
    if: (!failure()) && (((github.event_name == 'pull_request' || github.event_name == 'pull_request_target') && github.event.pull_request.base.ref == 'main') || (github.event_name == 'push' && github.event.ref == 'refs/heads/main'))
    needs: [production-plan]
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
      - uses: actions/github-script@v3.1.0
        with:
          script: |
            console.log('Deploying to Production')
